[package]
name = "awoo_derive"
version = "0.1.0"
authors = ["data-pup <kevinmartinucr@gmail.com>"]

[dependencies]
awoo = { path = "../awoo", version = "0.1.0" }
proc-macro2 = "0.4"
syn = "0.14.5"
quote = "0.6.4"

[lib]
proc-macro = true
